MVCproj/Controllers/ApplyCVController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCproj.Models;

namespace MVCproj.Controllers
{
    public class ApplyCVController : Controller
    {
        MVCproEntities dbobj = new MVCproEntities();
        
        // GET: ApplyCV
        public ActionResult cv_pageload()
        {
            return View();
        }
        public ActionResult apply_click(CVApply clsobj, HttpPostedFileBase file, FormCollection form)
        {
            var jobid = Session["jid"];
            int job_id = Convert.ToInt32(jobid);
            var user = Session["uid"];
            int user_id = Convert.ToInt32(user);
            if (file.ContentLength > 0)
            {
                string fname = Path.GetFileName(file.FileName);
                var s = Server.MapPath("~/rsme");
                string pa = Path.Combine(s, fname);
                file.SaveAs(pa);

                var fullpath = Path.Combine("//rsme", fname);
                clsobj.resume = fullpath;
            }
            DateTime date = clsobj.appdate;
            dbobj.sp_resumeApply(user_id, job_id, clsobj.resume, "Applied", date);
            clsobj.apmsg = "Applied!!";
            return View("cv_pageload", clsobj);
        }
    }
}

MVCproj/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCproj.Models;
using System.Data;
using System.Data.SqlClient;
using System.Configuration;

namespace MVCproj.Controllers
{
    public class SearchController : Controller
    {
        MVCproEntities dbobj = new MVCproEntities();
        // GET: Search
        public ActionResult Search_index()
        {
            return View(GetData());
        }
        private JobSearch GetData()
        {
            var joblist = new JobSearch();
            List<string> lst = new List<string>();
            var job = dbobj.jobs.ToList();
            foreach (var e in job)
            {
                var jobcls = new jsearch();
                DateTime date = e.closing_date;
                jobcls.job_id = e.job_id;
                jobcls.compid = e.comp_id;
                jobcls.skills = e.jb_skills;
                jobcls.jobdes = e.jb_des;
                jobcls.jstatus = e.status;
                jobcls.cdate = date.ToString();
                joblist.selectjob.Add(jobcls);
                var s = jobcls.skills;
                lst.Add(s);
                TempData["ski"] = string.Join(" ", lst);
                Session["jid"] = jobcls.job_id;
            }

            return joblist;
        }
        public ActionResult search_click(JobSearch clsobj)
        {
            string qry = " ";
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.jobdes))
            {
                qry += " and jb_des like '%" + clsobj.insertse.jobdes + "%'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.skills))
            {
                qry += " and jb_skills like '%" + clsobj.insertse.skills + "%'";
            }
            if (!string.IsNullOrWhiteSpace(clsobj.insertse.jstatus))
            {
                qry += " and status like '%" + clsobj.insertse.jstatus + "%'";
            }
            return View("Search_index", getdata(clsobj, qry));
        }

        private JobSearch getdata(JobSearch clsobj, string qry)
        {
            using (var con = new SqlConnection(ConfigurationManager.ConnectionStrings["con1"].ConnectionString))
            {
                SqlCommand cmd = new SqlCommand("sp_jv", con);
                cmd.CommandType = CommandType.StoredProcedure;
                cmd.Parameters.AddWithValue("@qry", qry);
                con.Open();
                SqlDataReader dr = cmd.ExecuteReader();
                var joblist = new JobSearch();
                while (dr.Read())
                {
                    var jobcls = new jsearch();
                    jobcls.compid = Convert.ToInt32(dr["comp_id"].ToString());
                    jobcls.skills = dr["jb_skills"].ToString();
                    jobcls.jobdes = dr["jb_des"].ToString();
                    jobcls.jstatus = dr["status"].ToString();
                    jobcls.cdate = dr["closing_date"].ToString();
                    joblist.selectjob.Add(jobcls);
                }
                con.Close();
                return joblist;
            }
        }

    }
}

MVCproj/Views/Search/Search_index.cshtml
@model MVCproj.Models.JobSearch
@{
    ViewBag.Title = "Search_index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Search</h2>
<div>
    @using (Html.BeginForm("search_click", "Search", FormMethod.Post))
    {

        <table>
            <tr>
                <td style="padding-left:8px;"><label>Skills:</label></td>
                <td>@Html.TextBoxFor(m => m.insertse.skills)</td>
                <td style="padding-left:8px;"><label>Description:</label></td>
                <td>@Html.TextBoxFor(m => m.insertse.jobdes)</td>
                <td style="padding-left:8px;"><label>Status:</label></td>
                <td>@Html.TextBoxFor(m => m.insertse.jstatus)</td>
                <td><input type="submit" value="Search" /></td>
            </tr>
        </table>
    }
</div>
<div>
    @using (Html.BeginForm("Search_index", "JobSearch", FormMethod.Get))
    {
        if (Model != null)
        {
            if (Model.selectjob != null && Model.selectjob.Count != 0)
            {
                <table class="table">
                    <tr>
                    </tr>
                    <tr>
                        <th>
                            @Html.DisplayNameFor(m => m.insertse.compid)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertse.skills)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertse.jobdes)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertse.jstatus)
                        </th>
                        <th>
                            @Html.DisplayNameFor(m => m.insertse.cdate)
                        </th>
                    </tr>
                    @foreach (var item in Model.selectjob)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.compid)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.skills)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.jobdes)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.jstatus)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.cdate)
                            </td>
                            <td>
                                @Html.ActionLink("ApplyNow", "cv_pageload", "ApplyCV", new { cid = item.compid, jid = item.job_id }, null)
                            </td>
                        </tr>
                    }
                </table>
            }
        }
    }
</div>