MVCproj/Controllers/CompRegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MVCproj.Models;

namespace MVCproj.Controllers
{
    public class CompRegController : Controller
    {
        MVCproEntities dboj = new MVCproEntities();
        // GET: CompReg
        public ActionResult insert_comp()
        {
            return View();
        }
        public ActionResult Comp_Insertclick(CompInsert clsobj)
        {
            if (ModelState.IsValid)
            {
                var getmaxId = dboj.sp_maxid().FirstOrDefault();
                int mid = Convert.ToInt32(getmaxId);
                int regid = 0;
                if (mid == 0)
                {
                    regid = 1;
                }
                else
                {
                    regid = mid + 1;
                }

                dboj.sp_CompanyInsert(regid, clsobj.Cname, clsobj.email, clsobj.phone, clsobj.address, clsobj.website);
                dboj.sp_login(regid, clsobj.username, clsobj.pass, "admin");
                clsobj.adminmsg = "Successfully Inserted";
                return View("insert_comp", clsobj);
            }
            return View("insert_comp", clsobj);
        }
    }
}

MVCproj/Views/CompReg/insert_comp.cshtml
@model MVCproj.Models.CompInsert
@{
    ViewBag.Title = "insert_comp";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Company Insertion</h2>
<div>
    @using (Html.BeginForm("Comp_Insertclick", "CompReg", FormMethod.Post))
    {
        <div>
            <label>Company Name:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.Cname)
            @Html.ValidationMessageFor(m => m.Cname)
        </div>
        <div>
            <label>E mail:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.email)
            @Html.ValidationMessageFor(m => m.email)
        </div>
        <div>
            <label>Phone:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.phone)
            @Html.ValidationMessageFor(m => m.phone)
        </div>
        <div>
            <label>Address:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.address)
            @Html.ValidationMessageFor(m => m.address)
        </div>
        <div>
            <label>Website:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.website)
            @Html.ValidationMessageFor(m => m.website)
        </div>
        <div>
            <label>User Name:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.username)
            @Html.ValidationMessageFor(m => m.username)
        </div>
        <div>
            <label>Password:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.pass)
        </div>
        <div>
            <label>Confirm Password:</label>
        </div>
        <div>
            @Html.TextBoxFor(m => m.cpassword)
            @Html.ValidationMessageFor(m => m.cpassword)
        </div>
        <div>
            <input type="submit" value="Insert" />
            @Html.DisplayFor(m => m.adminmsg)
        </div>
    }
</div>